//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace assignment2_draft.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("assignment2_draft.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AS,AirShaker
        ///AL,Always Late Airlines
        ///CA,Conned Air
        ///EC,Error Canada
        ///GA,Gypped Air
        ///MA,Mediocre Airlines
        ///OA,Otto Airlines
        ///SL,Scare Airlines
        ///ST,ScareTransat
        ///SW,Sprawl Airways
        ///TB,Try a Bus Airways
        ///VA,Vertical Airways.
        /// </summary>
        internal static string airlines {
            get {
                return ResourceManager.GetString("airlines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to YYC,Calgary International Airport
        ///YEG,Edmonton International Airport
        ///YUL,Montreal Pierre Elliott Trudeau International Airport
        ///YOW,Ottawa Macdonald-Cartier International Airport
        ///YYZ,Toronto Pearson International Airport
        ///YVR,Vancouver International Airport
        ///YWG,Winnipeg James Armstrong Richardson International Airport
        ///ATL,Hartsfield-Jackson Atlanta International Airport
        ///PEK,Beijing Capital International Airport
        ///DXB,Dubai International Airport
        ///HKG,Hong Kong International Airport
        ///LHR,London Heathrow  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string airports {
            get {
                return ResourceManager.GetString("airports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OA-9255,ORD,YUL,Monday,18:45,292,396.00
        ///TB-6339,YUL,FRA,Monday,1:15,169,741.00
        ///TB-6221,YEG,CDG,Sunday,21:00,169,1456.00
        ///OA-5943,YVR,YYC,Thursday,22:45,78,230.00
        ///TB-9974,FRA,DFW,Sunday,21:00,174,1160.00
        ///TB-8032,FRA,YEG,Sunday,2:15,292,686.00
        ///CA-1951,HKG,DFW,Thursday,17:45,255,714.00
        ///OA-7540,ORD,DEL,Wednesday,2:15,255,1197.00
        ///VA-5345,YWG,FRA,Tuesday,18:15,174,1139.00
        ///CA-7076,PEK,AMS,Thursday,21:15,255,924.00
        ///OA-5331,ATL,YUL,Saturday,21:15,292,446.00
        ///CA-6637,DEL,DFW,Friday,11:45,174,971.00
        ///VA-4453, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string flights {
            get {
                return ResourceManager.GetString("flights", resourceCulture);
            }
        }
    }
}
